
---

### 📄 File: `docker-compose.yml`

# yaml 
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: subtitle-backend
    volumes:
      - ./media:/app/media
      - ./backend:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: subtitle-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend
